Feat/clear manual rescheduling logs
open-spaced-repetition/fsrs4anki-helper pull request #488
Opened 2024-11-10 08:44 UTC by L-M-Sherlock

Patch:

[fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/17690719/fsrs4anki-helper.ankiaddon.zip)

2024-11-10 10:15 UTC, user1823 commented
Like https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/455, this should force a one-way sync.

2024-11-10 15:59 UTC, Luc-Mcgrady commented
![image](https://github.com/user-attachments/assets/65a5b6e5-4154-4e9a-8a63-dfbfe2ba607f)
It might be possible to separate from other schedule changes based on it having a usn of not -1.

2024-11-11 01:38 UTC, L-M-Sherlock commented
@user1823 nice catch. The last 90ed304 comment should solve it.

2024-11-11 07:21 UTC, L-M-Sherlock commented
@user1823 could you help me improve the wording?

2024-11-11 10:37 UTC, user1823 commented
Can you first explain what is the actual purpose of this feature? Is it aimed at removing just the "Reschedule cards on change" entries with the other entries being removed only because we can't keep them?

2024-11-11 10:55 UTC, L-M-Sherlock commented
Yes, it aims at removing the useless entires generated by "Reschedule cards on change". In extreme case, the percentage of this kind of useless entires will reach 25%.

@Expertium, I hope you can elaborate it: https://discord.com/channels/368267295601983490/1282005522513530952/1304016208080666634

2024-11-11 11:28 UTC, user1823 commented
In Anki 24.11+, we can distinguish between `Reschedule cards on change` and `Set due date` entries (only those entries which were created after the update). However, if we still have to use the same SQL query because the older entries are ambiguous, I am wondering what was the benefit of that change.

2024-11-11 11:38 UTC, user1823 commented
Probably we need to make it more configurable. I am thinking something along these lines:
- In Anki 24.11+, this feature should, by default, only remove the entries with `type = 5`.
- The user can choose to remove the older entries with the warning that it will also remove Set Due Date entries and a message that they need to select this option only once (because the newer Reschedule on change entries can be removed with the default query).

@Expertium, WDYT? If you agree, can you help in designing the UI for this?

2024-11-12 00:12 UTC, Luc-Mcgrady commented
What I've always thought would be a good solution for this would be to delete any manual review that comes directly before another manual review. That way the set due dates/reschedules that were never reviewed would be cleared while still leaving any reschedules/manual sets that actually matter.

Example:
![image](https://github.com/user-attachments/assets/a893a595-5d73-49c0-80ac-09cbb1226925)

2024-11-12 02:07 UTC, L-M-Sherlock commented
> What I've always thought would be a good solution for this would be to delete any manual review that comes directly before another manual review.

Could you help write the SQL? Or implement it in another way?

2024-11-12 08:50 UTC, Luc-Mcgrady commented
```sql
DELETE FROM revlog as cur
WHERE cur.type >= 4
AND cur.factor <> 0
AND (
	SELECT type
	FROM revlog
	WHERE id = (
		SELECT min(id)
		FROM revlog
		WHERE id > cur.id
		AND cid == cur.cid
	)
) >= 4
``` 
This should work

2024-11-13 12:15 UTC, user1823 requested changes

2024-11-13 12:15 UTC, user1823 commented on __init__.py
> +    clear_manual_rescheduling, "Clear manual rescheduling in all cards"
```suggestion
    clear_manual_rescheduling, "Delete redundant manual revlog entries"
```

2024-11-13 12:15 UTC, user1823 commented on schedule/reset.py
> +        "<p>Delete any manual review that comes directly before another manual review?</p>"
I suggest replacing all of this text by:

> This option removes revlog entries generated by "Set due date" and "Reschedule cards on change" that immediately precede another manual or reschedule entry. 
>
> This action cannot be undone. Do you want to continue?

2024-11-13 12:15 UTC, user1823 commented on schedule/reset.py
> +    tooltip("Review logs cleared.")
It would be better if we can also show the number of revlogs deleted.

2024-11-14 02:12 UTC, L-M-Sherlock commented
Done:

[fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/17741813/fsrs4anki-helper.ankiaddon.zip)

2024-11-14 07:05 UTC, khonkhortisan commented
Delete redundant manual revlog entries → force full sync? [yes] → remove revlog entries generated by "Set due date"? [no] → normal sync [y]. The yes/no dialogs should be in the other order, so that I'm locked into full syncing immediately after the full sync dialog.

2024-11-14 11:59 UTC, user1823 reviewed
- One minor wording suggestion
- I agree with the suggestion by khonkhortisan. The order of the two yes/no dialogs should be interchanged.
- Because the working of the option has changed, the name of the option (clear_manual_rescheduling) looks slightly incorrect.

After these are dealt with, I think that this PR can be merged.

2024-11-14 11:59 UTC, user1823 commented on schedule/reset.py
> +    tooltip(f"{cnt} review logs cleared.")
```suggestion
    tooltip(f"{cnt} review logs deleted.")
```

2024-11-14 12:51 UTC, L-M-Sherlock commented
Sorry, I'm confused. I think `force full sync` is necessary.

2024-11-14 13:03 UTC, user1823 commented
Yes, it is necessary.

But, move the full sync dialog AFTER you tell the user what this option does.

So,  `if not ask_one_way_sync(): return` comes just before `revlog_ids = mw.col.db.list(`

2024-11-14 13:12 UTC, L-M-Sherlock commented
cc

[fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/17749030/fsrs4anki-helper.ankiaddon.zip)

2024-11-14 21:04 UTC, khonkhortisan commented
Delete redundant manual revlog entries → force full sync? [yes] → remove revlog entries generated by "Set due date"? [no] → normal sync [y]. The yes/no dialogs should be in the other order, so that I'm locked into doing a full sync immediately after accepting.

2024-11-15 03:32 UTC, merged