Doc/introduce steps stats
open-spaced-repetition/fsrs4anki-helper pull request #499
Opened 2024-11-25 09:17 UTC by L-M-Sherlock

This discussion is useful to refer: https://forums.ankiweb.net/t/suggestion-about-the-learning-steps-after-analyzing-the-anki-dataset/51648/90?u=l.m.sherlock

2024-11-25 10:16 UTC, Expertium requested changes

2024-11-25 10:16 UTC, Expertium commented on README.md
> +The Steps Stats are based on all cards in your deck or collection (whichever is selected) that you have ever reviewed twice and the first review should be done in last 1 month/year or deck life.
```suggestion
The Steps Stats are based on all cards in your deck or collection (whichever is selected) that you have ever reviewed twice, and the first review was in the last 1 month/year or deck life.
```

2024-11-25 10:16 UTC, Expertium commented on README.md
> +This stats is helpful if you want to fine-tune your (re)learning steps to make the short-term schedule satisify your desired retention. For the mechanism about steps, please see the *Learning Steps*
```suggestion
These stats are helpful if you want to fine-tune your (re)learning steps to configure your short-term schedule according to your desired retention. If you want to learn more about learning steps, please read [this section of the Anki manual](https://docs.ankiweb.net/deck-options.html#learning-steps).
```

2024-11-25 11:23 UTC, user1823 commented on README.md
> +The Steps Stats are based on all cards in your deck or collection (whichever is selected) that you have ever reviewed twice, and the first review was in the last 1 month/year or deck life.
```suggestion
The Steps Stats are based on the cards from the selected deck or collection that were first reviewed in the last 1 month/year or deck life and have at least two reviews.
```

2024-11-25 11:23 UTC, user1823 commented on README.md
> +
```suggestion
These stats are helpful for fine-tuning your (re)learning steps to achieve your desired retention in the short-term reviews. To learn more about learning steps, please read [learning steps](https://docs.ankiweb.net/deck-options.html#learning-steps) in the  Anki manual.
```

2024-11-25 11:24 UTC, user1823 commented on README.md
> +These stats are helpful if you want to fine-tune your (re)learning steps to configure your short-term schedule according to your desired retention. If you want to learn more about learning steps, ple
```suggestion
These stats are helpful for fine-tuning your (re)learning steps to achieve your desired retention in the short-term reviews. To learn more about learning steps, please read [learning steps](https://docs.ankiweb.net/deck-options.html#learning-steps) in the  Anki manual.
```

2024-11-26 02:38 UTC, merged

2024-11-26 02:38 UTC, L-M-Sherlock commented
Thanks for you both!